language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run build
  - ls
  
deploy:
  provider: surge
  project: /dist/
  domain: outgoing-school.surge.sh
  skip_cleanup: true
  
